spring.application.name=doari
server.port=${SERVER_PORT:8080}

doari.services.usuarios-url=${USUARIOS_SERVICE_URL:http://localhost:8081}
doari.services.doacoes-url=${DOACOES_SERVICE_URL:http://localhost:8082}
doari.services.notificacoes-url=${NOTIFICACOES_SERVICE_URL:http://localhost:8083}
doari.public.notificacoes-url=${PUBLIC_NOTIFICACOES_URL:http://localhost:8083}
